// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnhWFmcp2ag-OgByGWVCTPXOtRWjwZb4A',
    appId: '1:757731914254:web:066eae7afbbe73ec4b825f',
    messagingSenderId: '757731914254',
    projectId: 'nomorewaste-ffb43',
    authDomain: 'nomorewaste-ffb43.firebaseapp.com',
    storageBucket: 'nomorewaste-ffb43.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3Xk8AQOQD0gb9_HVKrwYL2g4mTPwFhwg',
    appId: '1:757731914254:android:5016f3024d9465f34b825f',
    messagingSenderId: '757731914254',
    projectId: 'nomorewaste-ffb43',
    storageBucket: 'nomorewaste-ffb43.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBh7bXPsP1ZhB0JzkJ-7zlCZG_4ZSdrVBw',
    appId: '1:757731914254:ios:6ac73de237e1bf574b825f',
    messagingSenderId: '757731914254',
    projectId: 'nomorewaste-ffb43',
    storageBucket: 'nomorewaste-ffb43.firebasestorage.app',
    iosBundleId: 'com.example.wasteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBh7bXPsP1ZhB0JzkJ-7zlCZG_4ZSdrVBw',
    appId: '1:757731914254:ios:6ac73de237e1bf574b825f',
    messagingSenderId: '757731914254',
    projectId: 'nomorewaste-ffb43',
    storageBucket: 'nomorewaste-ffb43.firebasestorage.app',
    iosBundleId: 'com.example.wasteApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnhWFmcp2ag-OgByGWVCTPXOtRWjwZb4A',
    appId: '1:757731914254:web:b4d022cf905608674b825f',
    messagingSenderId: '757731914254',
    projectId: 'nomorewaste-ffb43',
    authDomain: 'nomorewaste-ffb43.firebaseapp.com',
    storageBucket: 'nomorewaste-ffb43.firebasestorage.app',
  );
}
